apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockeragent-deployment-windows
  labels:
    app: dockeragent-deployment-windows
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockeragent-windows
  template:
    metadata:
      labels:
        app: dockeragent-windows
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: dockeragent-windows
        image: <ACRNAME>.azurecr.io/dockeragent-windows:0.1
        ports:
        - containerPort: 80
        env:
        - name: AZP_URL
          value: "https://dev.azure.com/<ORGNAME>"
        - name: AZP_TOKEN
          value: <DEVOPSTOKEN>
        - name: AZP_AGENT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: AZP_POOL
          value: <NAMEOFWINDOWSPOOL>