# this is from https://github.com/HoussemDellai/build-agents-in-containers/blob/main/azure-pipelines.yaml
trigger:
- none

stages:
- stage: build

  pool:
   name: linux-containers-aks
   # vmImage: ubuntu-latest

  jobs:
  - job: buildApp

    strategy:
      matrix:
        build01:
          myVar: '1.0'
        build02:
          myVar: '1.0'
        build03:
          myVar: '1.0'
        build04:
          myVar: '1.0'
        build05:
          myVar: '1.0'
        build06:
          myVar: '1.0'
      maxParallel: 7

    steps:
    - script: |
        echo "Hello from inside Docker Container: $HOSTNAME"
        printenv

  # - job: buildApp02
  #   steps:
  #   - script: |
  #       echo "Hello from inside Docker Container: $HOSTNAME"
  #       printenv

  # - job: buildApp03
  #   steps:
  #   - script: |
  #       echo "Hello from inside Docker Container: $HOSTNAME"
  #       printenv